site_name: BC Gov API Services
docs_dir: documentation
repo_url: https://github.com/bcgov/aps-infra-platform
edit_uri: edit/main/documentation

nav:
  - "README.md"
  - Guides:
      - "guides/owner-journey.md"
      - "guides/owner-journey-v1.md"
      - "Client Credential Protection": "guides/tutorial-idp-client-cred-flow.md"
      - "Signed JWT w/ Certificate": "guides/intro-signed-jwt-pubkey.md"
      - "Signed JWT w/ Hosted JWKS": "guides/intro-signed-jwt.md"
      - "guides/keycloak-rbac.md"
      - "Query Kong Metrics (PQL": guides/prom-query.md
  - Resources:
      - "resources/api-access.md"
      - "resources/api-discovery.md"
      - "resources/cicd-integration.md"
      - "resources/gateway-admin.md"
      - "resources/gateway-configuration.md"
      - "resources/gwa-commands.md"
      - "resources/monitoring.md"
      - "resources/upstream-services.md"
  - Gateway:
      - "Supported Plugins": "gateway/AVAILABLE-PLUGINS.md"
      - "Common Controls": "gateway/COMMON-CONFIG.md"
      - Plugins:
          - "gateway/plugins/acl.md"
          - "gateway/plugins/cors.md"
          - "gateway/plugins/gwa-ip-anonymity.md"
          - "gateway/plugins/jwt-keycloak.md"
          - "gateway/plugins/key-auth.md"
          - "gateway/plugins/kong-upstream-auth-basic.md"
          - "gateway/plugins/kong-upstream-jwt.md"
          - "gateway/plugins/oidc.md"
          - "gateway/plugins/oidc-consumer.md"
          - "gateway/plugins/proxy-cache.md"
          - "gateway/plugins/rate-limiting.md"
          - "gateway/plugins/request-transformer.md"
          - "gateway/plugins/waiting-queue.md"
      - "gateway/SSL.md"
  - Reference:
      - "reference/glossary.md"
      - Releases:
        - "reference/releases/index.md"
        - "reference/releases/2023-nov-1.2.15.md"
        - "reference/releases/2023-sept-1.2.14.md"
        - "reference/releases/2023-jun-1.2.12.md"
        - "reference/releases/2023-mar-1.2.11.md"
        - "reference/releases/2023-jan-1.2.6.md"
        - "reference/releases/2022-oct-1.2.5.md"
        - "reference/releases/2022-sept-1.2.4.md"
        - "reference/releases/2022-sept.md"
        - "reference/releases/2022-aug.md"
        - "reference/releases/2022-may.md"
        - "reference/releases/2021-jun.md"
      - Portal User Cases:
        - "reference/portal-use-cases/login.md"
        - "reference/portal-use-cases/create-service-account.md"
        - "reference/portal-use-cases/switch-namespace.md"
        - "reference/portal-use-cases/access.md"
        - "reference/portal-use-cases/consumer-maintenance.md"
        - "reference/portal-use-cases/websequencediagrams.md"
      - "reference/presentations.md"
  - "external-resources.md"

plugins:
  - techdocs-core
