site_name: BC Gov API Services
docs_dir: documentation
repo_url: https://github.com/bcgov/aps-infra-platform
edit_uri: blob/test/documentation

nav:
  - "README.md"
  - Tutorials:
      - "tutorials/quick-start.md"
  - How-to Guides:
      - "how-to/gwa-install.md"
      - "how-to/create-gateway-service.md"
      - "how-to/private-route.md"
      - "how-to/generate-service-account.md"
      - "how-to/api-discovery.md"
      - "how-to/protected-externally.md"
      - "how-to/client-cred-flow.md"
      - "how-to/AVAILABLE-PLUGINS.md"
      - "how-to/COMMON-CONFIG.md"
      - "how-to/SSL.md"
      - "how-to/intro-signed-jwt-pubkey.md"
      - "how-to/intro-signed-jwt.md"
      - "how-to/keycloak-rbac.md"
      - "how-to/prom-query.md"
      - "how-to/api-access.md"
      - "how-to/cicd-integration.md"
      - "how-to/gateway-admin.md"
      - "how-to/gwa-commands.md"
      - "how-to/monitoring.md"
      - "how-to/upstream-services.md"
  - Concepts:
      - "concepts/api-directory.md"
  - Reference:
      - Plugins:
          - "reference/plugins/acl.md"
          - "reference/plugins/cors.md"
          - "reference/plugins/gwa-ip-anonymity.md"
          - "reference/plugins/jwt-keycloak.md"
          - "reference/plugins/key-auth.md"
          - "reference/plugins/kong-upstream-auth-basic.md"
          - "reference/plugins/kong-upstream-jwt.md"
          - "reference/plugins/oidc.md"
          - "reference/plugins/oidc-consumer.md"
          - "reference/plugins/proxy-cache.md"
          - "reference/plugins/rate-limiting.md"
          - "reference/plugins/request-transformer.md"
          - "reference/plugins/waiting-queue.md"
      - "reference/glossary.md"
      - "reference/releases/index.md"
      - Portal User Cases:
        - "reference/portal-use-cases/login.md"
        - "reference/portal-use-cases/create-service-account.md"
        - "reference/portal-use-cases/switch-namespace.md"
        - "reference/portal-use-cases/access.md"
        - "reference/portal-use-cases/consumer-maintenance.md"
        - "reference/portal-use-cases/websequencediagrams.md"
      - "reference/presentations.md"
  - Contribute:
      - "contribute/style-guide.md"
  - "external-resources.md"


plugins:
  - techdocs-core
  - ezlinks
  - git-revision-date-localized

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.tasklist:
    #   custom_checkbox: true
      clickable_checkbox: true
