import os
import yaml
import re
import sys

DOCS_URL = os.getenv('DOCS_URL', 'https://developer.gov.bc.ca/docs/default/component/aps-infra-platform-docs')

"""
This script uses a central glossary reference YAML file to generate the glossary
page and substitute tooltips for special glossary references 
({{ glossary_tooltip ... }}) throughout the documentation Markdown files. It ensures
glossary terms remain consistent, linked, and up to date across all relevant
documentation. See the README.md file for more details on how to use the
glossary references in the documentation.

This script is used by the publish-techdocs.yaml GitHub Actions workflow to
generate the updated pages for publishing to DevHub.

To update the glossary page stored in source control (not the page actually
published to DevHub) run this script to generate the glossary page 
(`python scripts/sub_glossary.py`) and commit the updated glossary page to the repository.

DO NOT commit all substituted Markdown files, only the glossary page.
"""

def load_definitions(config_file):
    try:
        with open(config_file, 'r') as f:
            config = f.read()
            config = config.replace('{DOCS_URL}', DOCS_URL)
            config = yaml.safe_load(config)
            return config.get("terms", {})
    except Exception as e:
        print("Error loading configuration file:", e)
        sys.exit(1)

def substitute_links(markdown_file, definitions):
    try:
        with open(markdown_file, 'r') as f:
            content = f.read()

        for term_id, term_data in definitions.items():
            pattern = r'\{\{ glossary_tooltip term_id="' + term_id + r'"\s*(?:text="([^"]+)")?\s*\}\}'            
            matches = re.findall(pattern, content)

            for match in matches:
                 # Use name if text is not provided
                term_text = match if match else term_data["name"]

                if term_data["url"]:
                    link_tag = f'<a href="{term_data["url"]}" title="{term_data["def"]}" target="_blank" style="text-decoration: none !important; color: inherit; border-bottom: 1px dotted;">{term_text}</a>'
                else:
                    # If no url, just create tooltip
                    link_tag = f'<span title="{term_data["def"]}" style="border-bottom: 1px dotted;">{term_text}</span>'
                
                # Replace the placeholder with the link tag
                content = re.sub(pattern, link_tag, content, count=1)

        return content
    except Exception as e:
        print("Error substituting links in", markdown_file, ":", e)
        sys.exit(1)

def process_markdown_files(root_folder, definitions):
    for root, dirs, files in os.walk(root_folder):
        for file in files:
            if file.endswith(".md"):
                markdown_file = os.path.join(root, file)
                try:
                    modified_content = substitute_links(markdown_file, definitions)         
                    with open(markdown_file, 'w') as f:
                        f.write(modified_content)
                    print("Links substituted successfully in", markdown_file)
                except Exception as e:
                    print("Error processing", markdown_file, ":", e)

def yaml_to_md_glossary(yaml_file):
    with open(yaml_file, 'r') as f:
        data = f.read()
        data = data.replace('{DOCS_URL}', DOCS_URL)
        data = yaml.safe_load(data)
    
    # append a comment to the top of the file about the source of the glossary
    file_header = """---\ntitle: Glossary\n---\n
<!--
This glossary was generated from the glossary_reference.yaml file in the scripts folder.
Do not edit this file directly, edit the glossary_reference.yaml file instead.
-->\n
"""

    markdown_table = file_header + "|Term|Definition|\n|:----|:----|\n"
    
    for term, details in data['terms'].items():
        markdown_table += f"|{details['name']}|{details['def']}|\n"
    
    return markdown_table

def save_to_file(markdown_table, output_file):
    with open(output_file, 'w') as f:
        f.write(markdown_table)
    print("Glossary created at:", output_file)

def main():
    reference_file = 'scripts/glossary_reference.yaml'
    definitions = load_definitions(reference_file)
    
    # produce glossary
    markdown_table = yaml_to_md_glossary(reference_file)
    output_file = 'documentation/reference/glossary.md'
    save_to_file(markdown_table, output_file)

    # substitute docs
    documentation_folder = 'documentation'
    process_markdown_files(documentation_folder, definitions)

if __name__ == "__main__":
    main()
