on:
  push:
    branches: validate-cli

env:
  NS: "gw-6328f"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 10
          TOKEN: ${ {secrets.GITHUB_TOKEN} }

      - name: Get GWA Command Line
        run: |

          curl -L https://github.com/bcgov/gwa-cli/releases/download/v2.0.4/gwa_Linux_x86_64.tgz | tar -zxf -
          export PATH=$PATH:$PWD

      - name: Apply Namespace Configuration
        run: |
          export PATH=`pwd`:$PATH
          cd .gwa/$NS

          # include only if working in the test/training environment
          gwa config set host api-gov-bc-ca.test.api.gov.bc.ca

          gwa config set namespace $NS
          gwa login \
            --client-id=${ { secrets.GWA_ACCT_ID } } \
            --client-secret=${ { secrets.GWA_ACCT_SECRET } }

          gwa pg

          
