name: Publish TechDocs

on:
  push:
    branches: [ test, main, APS-2409-sub-glossary ]
    paths:
      - "documentation/**"
      - "mkdocs.yml"
      - "catalog-info.yaml"
  workflow_dispatch:
    inputs:
      deploy_location:
        description: "Deploy to"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    name: Build and publish techdocs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run python Script
        run: python scripts/sub_glossary.py
      - name: Build TechDocs
        uses: bcgov/devhub-techdocs-publish@stable
        id: build_and_publish
        with:
          publish: 'true'
          production: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }} 
          bucket_name: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
          s3_access_key_id: ${{ secrets.TECHDOCS_AWS_ACCESS_KEY_ID }}
          s3_secret_access_key: ${{ secrets.TECHDOCS_AWS_SECRET_ACCESS_KEY }}
          s3_region: ${{ secrets.TECHDOCS_AWS_REGION }}
          s3_endpoint: ${{ secrets.TECHDOCS_AWS_ENDPOINT }}
